name: SurgViVQAEnv
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.5.0=h27087fc_0
  - aws-c-auth=0.7.22=h96bc93b_2
  - aws-c-cal=0.6.14=h88a6e22_1
  - aws-c-common=0.9.19=h4ab18f5_0
  - aws-c-compression=0.2.18=h83b837d_6
  - aws-c-event-stream=0.4.2=ha47c788_12
  - aws-c-http=0.8.1=h29d6fba_17
  - aws-c-io=0.14.8=h21d4f22_5
  - aws-c-mqtt=0.10.4=h759edc4_4
  - aws-c-s3=0.5.9=h594631b_3
  - aws-c-sdkutils=0.1.16=h83b837d_2
  - aws-checksums=0.1.18=h83b837d_6
  - aws-crt-cpp=0.26.9=he3a8b3b_0
  - aws-sdk-cpp=1.11.329=hba8bd5f_3
  - binutils_impl_linux-64=2.40=h5293946_0
  - binutils_linux-64=2.40=hb3c18ed_9
  - blas=1.0=mkl
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cmake=3.21.3=h8897547_0
  - expat=2.7.1=h6a678d5_0
  - ffmpeg=5.1.2=gpl_h8dda1f0_106
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.1=h55d465d_3
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=h267a509_2
  - gcc_impl_linux-64=15.1.0=h4393ad2_4
  - gcc_linux-64=15.1.0=h1ac4077_11
  - gflags=2.2.2=h5888daf_1005
  - glog=0.7.1=hbabe93e_0
  - gmp=6.3.0=hac33072_2
  - gnutls=3.7.9=hb077bed_0
  - gxx_impl_linux-64=15.1.0=h6a1bac1_4
  - gxx_linux-64=15.1.0=h1a088d8_11
  - icu=73.2=h59595ed_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.20.1=h81ceb04_0
  - lame=3.100=h166bdaf_1003
  - ld_impl_linux-64=2.40=h12ee557_0
  - libabseil=20240116.2=cxx17_he02047a_1
  - libarrow=16.1.0=hcb6531f_6_cpu
  - libarrow-acero=16.1.0=hac33072_6_cpu
  - libarrow-dataset=16.1.0=hac33072_6_cpu
  - libarrow-substrait=16.1.0=h7e0c224_6_cpu
  - libasprintf=0.25.1=h3f43e3d_1
  - libbrotlicommon=1.1.0=hb9d3cd8_3
  - libbrotlidec=1.1.0=hb9d3cd8_3
  - libbrotlienc=1.1.0=hb9d3cd8_3
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcurl=8.9.1=h251f7ec_0
  - libdrm=2.4.125=hb9d3cd8_0
  - libedit=3.1.20191231=he28a2e2_2
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=h516909a_1
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.1.0=h767d61c_3
  - libgcc-devel_linux-64=15.1.0=h4c094af_104
  - libgcc-ng=15.1.0=h69a702a_3
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgfortran-ng=8.2.0=hdf63c60_1
  - libgfortran5=15.1.0=hcea5267_3
  - libgl=1.7.0=ha4b6fd6_2
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.1.0=h767d61c_3
  - libgoogle-cloud=2.24.0=h2736e30_0
  - libgoogle-cloud-storage=2.24.0=h3d9a0c8_0
  - libgrpc=1.62.2=h15f2491_0
  - libiconv=1.18=h3b78370_2
  - libidn2=2.3.8=ha4ef2c3_0
  - libnghttp2=1.58.0=h47da74e_1
  - libopenblas=0.3.29=ha39b09d_0
  - libopus=1.5.2=hd0c01bc_0
  - libparquet=16.1.0=h6a7eafb_6_cpu
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.43=h2797004_0
  - libprotobuf=4.25.3=h08a7969_0
  - libre2-11=2023.09.01=h5a48ba9_2
  - libsanitizer=15.1.0=h97b714f_4
  - libssh2=1.10.0=ha35d2d1_2
  - libstdcxx=15.1.0=h8f9b012_3
  - libstdcxx-devel_linux-64=15.1.0=h4c094af_104
  - libstdcxx-ng=15.1.0=h4852527_3
  - libtasn1=4.20.0=hb9d3cd8_0
  - libthrift=0.19.0=hb90f79a_1
  - libunistring=0.9.10=h7f98852_0
  - libutf8proc=2.8.0=hf23e847_1
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.43.0=h7f98852_0
  - libva=2.22.0=h4f16b4b_2
  - libvpx=1.11.0=h9c3ff4c_3
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.8=hfdd30dd_0
  - libzlib=1.2.13=h4ab18f5_6
  - lz4-c=1.9.3=h9c3ff4c_1
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_2
  - mkl_fft=1.3.11=py310h5eee18b_0
  - mkl_random=1.2.8=py310h1128e8f_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.9.1=h7ab15ed_0
  - numpy=2.0.1=py310h5f9d8c6_1
  - numpy-base=2.0.1=py310hb5e798b_1
  - openh264=2.3.1=hcb278e6_2
  - openssl=3.5.4=h26f9b46_0
  - orc=2.0.1=h17fec99_1
  - p11-kit=0.24.1=hc5aa10d_0
  - pip=25.1=pyhc872135_2
  - pkg-config=0.29.2=h4bc722e_1009
  - pthread-stubs=0.3=h0ce48e5_1
  - pyarrow=16.1.0=py310hb7f781d_2
  - pyarrow-core=16.1.0=py310hcccf80d_2_cpu
  - python=3.10.18=h1a3bd86_0
  - python_abi=3.10=2_cp310
  - re2=2023.09.01=h7f4b329_2
  - readline=8.2=h5eee18b_0
  - rhash=1.4.1=h7f98852_0
  - s2n=1.4.15=he19d79f_0
  - scikit-learn=1.7.1=py310hc74f9fe_0
  - scipy=1.15.3=py310h525edd1_0
  - setuptools=78.1.1=py310h06a4308_0
  - snappy=1.2.2=h03e3b7b_0
  - sqlite=3.50.2=hb25bd0a_1
  - svt-av1=1.4.1=hcb278e6_0
  - sysroot_linux-64=2.17=h0157908_18
  - tbb=2021.8.0=hdb19cb5_0
  - threadpoolctl=3.5.0=py310h2f386ee_0
  - tk=8.6.14=h993c535_1
  - wayland=1.23.1=h3e06ad9_0
  - wayland-protocols=1.45=hd8ed1ab_0
  - wheel=0.45.1=py310h06a4308_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - absl-py==2.3.1
      - accelerate==1.9.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.14
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - beautifulsoup4==4.13.5
      - certifi==2025.7.14
      - charset-normalizer==3.4.2
      - click==8.2.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - datasets==4.0.0
      - decord==0.6.0
      - deepspeed==0.17.4
      - dill==0.3.8
      - easydict==1.13
      - einops==0.8.1
      - evaluate==0.4.5
      - ffmpeg-python==0.2.0
      - filelock==3.18.0
      - fonttools==4.59.0
      - frozenlist==1.7.0
      - fsspec==2025.3.0
      - future==1.0.0
      - fvcore==0.1.5.post20221221
      - gdown==5.2.0
      - hf-xet==1.1.5
      - hjson==3.1.0
      - huggingface-hub==0.34.4
      - idna==3.10
      - imageio==2.37.0
      - iopath==0.1.10
      - jinja2==3.1.6
      - joblib==1.5.1
      - kiwisolver==1.4.8
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - mpmath==1.3.0
      - msgpack==1.1.1
      - multidict==6.6.3
      - multiprocess==0.70.16
      - networkx==3.4.2
      - ninja==1.11.1.4
      - nltk==3.9.1
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pandas==2.3.1
      - peft==0.16.0
      - pillow==11.3.0
      - portalocker==3.2.0
      - propcache==0.3.2
      - protobuf==6.33.0
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyparsing==3.2.3
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.4
      - rouge-score==0.1.2
      - safetensors==0.5.3
      - six==1.17.0
      - soupsieve==2.8
      - sympy==1.13.1
      - tabulate==0.9.0
      - termcolor==3.1.0
      - timm==1.0.19
      - tokenizers==0.21.0
      - torch==2.6.0
      - torchvision==0.21.0
      - tqdm==4.67.1
      - transformers==4.55.4
      - triton==3.2.0
      - typing-extensions==4.14.1
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - xxhash==3.5.0
      - yacs==0.1.8
      - yarl==1.20.1
prefix: /SAN/medic/Kvasir/miniconda3/envs/SurgViVQAEnv
